### ISSUE TITLE
Add constant tuning and data output setup to Shuffleboard sections

### ISSUE THREAD

**Issue by matth101** [FRC1257/robotics-training#14]
i.e. for loops w/ ArrayList<SnailSubsystem> and outputCounter in RobotContainer

**Comment by rcya1** [comment]
I don't think I really want to do this in those sections (maybe in the advanced section) since it's something most beginner programmers don't have to worry with at all. If I do include it, it will be in the advanced section for maybe those interested in advancing to captain / maintainer of the entire project.

**Comment by matth101** [comment]
Sounds good.
